from datetime import UTC, datetime
from pathlib import Path

import numpy as np
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from oure.core.models import ConjunctionEvent, OptimizationResult


class ConjunctionReportGenerator:
    """Generates a PDF mission report for a conjunction event."""

    def generate(
        self,
        event: ConjunctionEvent,
        maneuver: OptimizationResult | None,
        output_path: Path,
    ) -> None:
        c = canvas.Canvas(str(output_path), pagesize=letter)
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, 750, "OURE Conjunction Mission Report")

        c.setFont("Helvetica", 12)
        c.drawString(
            50, 720, f"Generated: {datetime.now(UTC).strftime('%Y-%m-%dT%H:%M:%S')}Z"
        )

        # 1. Executive Summary
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, 680, "1. Executive Summary")
        c.setFont("Helvetica", 12)
        from oure.risk.calculator import RiskCalculator

        calc = RiskCalculator()
        res = calc.compute_pc(event)

        c.drawString(50, 660, f"Probability of Collision (Pc): {res.pc:.4e}")
        if res.warning_level == "RED":
            c.setFillColor(colors.red)
            c.drawString(300, 660, "[ACTION REQUIRED]")
            c.setFillColor(colors.black)
        elif res.warning_level == "YELLOW":
            c.setFillColor(colors.orange)
            c.drawString(300, 660, "[MONITOR]")
            c.setFillColor(colors.black)
        else:
            c.setFillColor(colors.green)
            c.drawString(300, 660, "[NOMINAL]")
            c.setFillColor(colors.black)

        c.drawString(
            50,
            640,
            f"Time of Closest Approach (TCA): {event.tca.strftime('%Y-%m-%dT%H:%M:%S')}Z",
        )
        c.drawString(50, 620, f"Miss Distance: {event.miss_distance_km:.2f} km")
        c.drawString(
            50, 600, f"Relative Velocity: {event.relative_velocity_km_s:.2f} km/s"
        )

        # 2. Object details
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, 560, "2. Object Details")
        c.setFont("Helvetica", 12)
        c.drawString(50, 540, f"Primary Object (NORAD ID): {event.primary_id}")
        c.drawString(
            50,
            520,
            f"Primary Altitude: {np.linalg.norm(event.primary_state.r) - 6371.0:.2f} km",
        )
        c.drawString(50, 500, f"Secondary Object (NORAD ID): {event.secondary_id}")
        c.drawString(
            50,
            480,
            f"Secondary Altitude: {np.linalg.norm(event.secondary_state.r) - 6371.0:.2f} km",
        )

        # 3. Uncertainty analysis
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, 440, "3. Uncertainty Analysis (B-Plane)")
        c.setFont("Helvetica", 12)
        c.drawString(50, 420, f"Sigma X: {res.b_plane_sigma_x * 1000.0:.2f} m")
        c.drawString(50, 400, f"Sigma Z: {res.b_plane_sigma_z * 1000.0:.2f} m")

        # 4. Maneuver recommendation
        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, 360, "4. Maneuver Recommendation")
        c.setFont("Helvetica", 12)
        if maneuver and maneuver.success:
            burn_epoch_str = (
                maneuver.burn_epoch.strftime("%Y-%m-%dT%H:%M:%S") + "Z"
                if maneuver.burn_epoch
                else "N/A"
            )
            c.drawString(50, 340, f"Burn Epoch: {burn_epoch_str}")
            c.drawString(
                50,
                320,
                f"Delta-V (km/s): [{maneuver.optimal_dv_km_s[0]:.6f}, {maneuver.optimal_dv_km_s[1]:.6f}, {maneuver.optimal_dv_km_s[2]:.6f}]",
            )
            c.drawString(
                50, 300, f"Estimated Fuel Cost: {maneuver.fuel_cost_kg:.2f} kg"
            )
            c.drawString(50, 280, f"Post-Maneuver Pc: {maneuver.final_pc:.4e}")
            c.drawString(
                50,
                260,
                f"Station Keeping Preserved: {'Yes' if maneuver.station_keeping_ok else 'No'}",
            )
        else:
            c.drawString(50, 340, "No maneuver computed or required.")

        c.setFont("Helvetica-Bold", 14)
        c.drawString(50, 220, "5. Metadata")
        c.setFont("Helvetica", 12)
        c.drawString(50, 200, "Generated by OURE - Orbital Uncertainty & Risk Engine")

        c.save()
