"""
OURE CLI - Plot Command
=======================
"""

import json
import sys
from pathlib import Path

import click

from oure.risk.plotter import RiskPlotter

from .main import cli
from .utils import UI


@cli.command()
@click.option(
    "--results-file",
    type=click.Path(exists=True),
    required=True,
    help="JSON file generated by the analyze command.",
)
@click.option(
    "--event-idx",
    type=int,
    default=1,
    help="Which event in the file to plot (1-indexed).",
)
@click.option(
    "--output",
    "-o",
    type=click.Path(),
    default="bplane_plot.html",
    help="Output HTML file path.",
)
def plot(results_file: str, event_idx: int, output: str) -> None:
    """
    Generate an interactive 2D B-Plane cross-section plot of the collision probability.
    """
    UI.header("Risk Visualization", f"Plotting event #{event_idx} from {results_file}")

    try:
        with open(results_file) as f:
            data = json.load(f)
    except Exception as e:
        UI.error(f"Failed to read results file: {e}")
        sys.exit(1)

    if not data:
        UI.error("No results found in the input file.")
        return

    if event_idx < 1 or event_idx > len(data):
        UI.error(
            f"Invalid event index {event_idx}.", f"File contains {len(data)} events."
        )
        sys.exit(1)

    # Convert 1-indexed to 0-indexed
    event_data = data[event_idx - 1]

    out_path = Path(output)
    try:
        RiskPlotter.plot_bplane_from_json(event_data, out_path)
        UI.success(f"Plot generated successfully: {out_path.absolute()}")
    except Exception as e:
        UI.error(f"Plotting failed: {e}")
